build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
filter:
    paths: [lib/*]
    excluded_paths:
      - tests/
      - vendor/
      - build/
      - tools/
      - docs/
checks:
  php:
    code_rating: true
    excluded_dependencies:
            - composer/xdebug-handler
            - doctrine/annotations
            - friendsofphp/php-cs-fixer
            - phpspec/prophecy
            - phpunit/php-code-coverage
            - phpunit/php-text-template
            - phpunit/php-timer
            - phpunit/phpunit
            - sebastian/code-unit
            - sebastian/comparator
            - sebastian/complexity
            - sebastian/diff
            - sebastian/exporter
            - sebastian/global-state
            - sebastian/lines-of-code
            - sebastian/object-enumerator
            - sebastian/object-reflector
            - sebastian/recursion-context
            - sebastian/type
            - squizlabs/php_codesniffer
            - symfony/console
            - symfony/event-dispatcher
            - symfony/filesystem
            - symfony/options-resolver
            - symfony/polyfill-ctype
            - symfony/polyfill-intl-grapheme
            - symfony/polyfill-intl-normalizer
            - symfony/polyfill-mbstring
            - symfony/polyfill-php72
            - symfony/polyfill-php73
            - symfony/polyfill-php80
            - symfony/process
            - symfony/string
            - webmozart/assert
            - yoast/phpunit-polyfills
tools:
  php_analyzer:
    enabled: true
    extensions:
        - php
  external_code_coverage:
    timeout: 1200
    runs: 1
  php_code_coverage: false
  php_code_sniffer:
    config:
      standard: PSR2
    filter:
      paths: ['lib']
  php_loc:
    enabled: true
    excluded_dirs: [vendor, spec]
  sensiolabs_security_checker:
    enabled: true